// Generated by CoffeeScript 1.7.1
var Express, app, bodyParser, http, jsonParser, lastPath, moment, path, request;

http = require("http");

Express = require("express");

request = require('request');

moment = require('moment');

path = require('path');

bodyParser = require('body-parser');

jsonParser = bodyParser.json();

app = Express();

app.set("port", process.env.PORT || 5294);

app.set("views", path.join(__dirname, "views"));

app.set("view engine", "jade");

lastPath = [];

app.post("/print", jsonParser, function(req, res) {
  console.log(JSON.stringify(req.body));
  lastPath = req.body;
});

app.get("/path", function(req, res) {
  res.send(JSON.stringify(lastPath));
  return console.log("Sending path");
});

app.use("/", Express["static"](path.join(__dirname, '../../App/WebApp/www')));

app.use("/test", Express["static"](path.join(__dirname, 'public')));

app.use(function(req, res) {
  res.render("404", {
    url: req.url
  });
});

http.createServer(app).listen(app.get("port"), function() {
  console.log("PancakeBot2D test server listening on port " + app.get("port"));
});
