// Generated by CoffeeScript 1.7.1
var Express, app, bodyParser, http, moment, path, strokesToPrint, textParser;

http = require("http");

Express = require("express");

moment = require('moment');

path = require('path');

bodyParser = require('body-parser');

textParser = bodyParser.text();

app = Express();

app.set("port", process.env.PORT || 5294);

app.set("views", path.join(__dirname, "views"));

app.set("view engine", "jade");

strokesToPrint = "";

app.post("/printinit", textParser, function(req, res) {
  strokesToPrint = req.body;
  res.send("OK");
});

app.post("/printpart", textParser, function(req, res) {
  strokesToPrint += req.body;
  res.send("OK");
});

app.post("/printgo", textParser, function(req, res) {
  var strokes;
  strokesToPrint += req.body;
  console.log(strokesToPrint);
  strokes = JSON.parse(strokesToPrint);
  console.log("Num strokes " + strokes.length);
  res.send("OK");
});

app.post("/printinitgo", textParser, function(req, res) {
  var strokes;
  strokesToPrint = req.body;
  console.log(strokesToPrint);
  strokes = JSON.parse(strokesToPrint);
  console.log("Num strokes " + strokes.length);
  res.send("OK");
});

app.get("/path", function(req, res) {
  res.send(JSON.stringify(lastPath));
  return console.log("Sending path");
});

app.use("/", Express["static"](path.join(__dirname, '../../App/WebApp/www')));

app.use("/test", Express["static"](path.join(__dirname, 'public')));

app.use(function(req, res) {
  res.render("404", {
    url: req.url
  });
});

http.createServer(app).listen(app.get("port"), function() {
  console.log("PancakeBot2D test server listening on port " + app.get("port"));
});
